apiVersion: apps/v1
kind: Deployment
metadata:
  namespace : expense
  name: backend
  labels:
    project: expense
    environment: dev
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      environment: dev
      component: backend
  template:
    metadata:
      labels:
        project: expense
        environment: dev
        component: backend
    spec:
      containers:
      - name: backend
        image: vishnupriyadh/backend:1.0.0

---
# backend-service is created for connectivity between backend and backend
# Attach service to backend
apiVersion: v1
kind : Service
metadata:
  name: backend
  namespace: expense
spec:
  selector: # labels are used as selctor
    project: expense
    environment: dev
    component: backend
  ports:
  - protocol: TCP
    port: 8080 # service port 
    targetPort: 8080 # Pod port 






  